name: Release
concurrency: ci-${{ github.ref }}
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: 17
            - uses: gradle/gradle-build-action@v2
              with:
                  arguments: checkLicenses build
                  cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
            - uses: gradle/gradle-build-action@v2
              with:
                  arguments: publish
                  cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
              env:
                  MAVEN_USER: ${{ secrets.MAVEN_USER }}
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
